### ISSUE TITLE
Count value limitation

### ISSUE THREAD

**Issue by fboilot** [SoftwareAG/cumulocity-device-chart-widget#4]
Hi

I want to use this widget to count the number of devices grouped by type. I've more than 100 devices having type X. But the widget count max value seems limited to 100. If I have 150 devices in my group with type X, the widget display 100 instead of 150. Is there any count limitation?    

Thanks for your feeback

![Device-count](https://user-images.githubusercontent.com/85934050/144286512-f5c1c660-f794-4432-8a93-2aaca3e8fa10.JPG)

**Comment by fboilot** [comment]
@

**Comment by sandhyadeeps** [comment]
Issue fixed. 

Please use release 1.1.1
Page size has been updated to 2000.

**Comment by fboilot** [comment]
It works fine with the new page size. Thanks a lot.
